// SPDX-FileCopyrightText: 2024 Nextcloud Wallpaper Plugin
// SPDX-License-Identifier: GPL-2.0-or-later

// Stub file for plasma_potd_export.h
// This file is normally generated by CMake when building kdeplasma-addons
// For standalone builds, we provide a minimal stub

#ifndef PLASMA_POTD_EXPORT_H
#define PLASMA_POTD_EXPORT_H

// Define PLASMA_POTD_EXPORT macro
// For plugins, we don't need special export handling
#ifndef PLASMA_POTD_EXPORT
#  if defined(MAKE_PLASMA_POTD_LIB)
#    define PLASMA_POTD_EXPORT Q_DECL_EXPORT
#  else
#    define PLASMA_POTD_EXPORT Q_DECL_IMPORT
#  endif
#  ifndef PLASMA_POTD_EXPORT_DEPRECATED
#    define PLASMA_POTD_EXPORT_DEPRECATED PLASMA_POTD_EXPORT
#  endif
#endif

#endif // PLASMA_POTD_EXPORT_H

